### ISSUE TITLE
Handle non-existent relation "genericm2m_relatedobject"

### ISSUE THREAD

**Issue by blueyed** [coleifer/django-generic-m2m#17]
I have received the following error when applying the migrations for an app:

    ProgrammingError: relation "genericm2m_relatedobject" does not exist

The problem appears to be that genericm2m is installed in the virtualenv
and gets imported from `autocomplete_light`, but its tables do not exist.

I think that genericm2m should handle the case where its table/relation
does not exist. This might happen in other cases, too.

genericm2m does not show up in the Traceback itself. This might be due to
the signal handling?!

    The following content types are stale and need to be deleted:

        app | foofile
        …

    Any objects related to these content types by a foreign key will also
    be deleted. Are you sure you want to delete these content types?
    If you're unsure, answer 'no'.

        Type 'yes' to continue, or 'no' to cancel: yes
    Traceback (most recent call last):
      File "…/src/manage.py", line 37, in <module>
        execute_from_command_line(sys.argv)
      File "venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
        utility.execute()
      File "venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
        self.fetch_command(subcommand).run_from_argv(self.argv)
      File "venv/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
        self.execute(*args, **options.__dict__)
      File "venv/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
        output = self.handle(*args, **options)
      File "venv/lib/python2.7/site-packages/south/management/commands/migrate.py", line 111, in handle
        ignore_ghosts = ignore_ghosts,
      File "venv/lib/python2.7/site-packages/south/migration/__init__.py", line 220, in migrate_app
        success = migrator.migrate_many(target, workplan, database)
      File "venv/lib/python2.7/site-packages/south/migration/migrators.py", line 254, in migrate_many
        result = migrator.__class__.migrate_many(migrator, target, migrations, database)
      File "venv/lib/python2.7/site-packages/south/migration/migrators.py", line 335, in migrate_many
        interactive=self.interactive)
      File "venv/lib/python2.7/site-packages/south/db/generic.py", line 1030, in send_pending_create_signals
        interactive=interactive)
      File "venv/lib/python2.7/site-packages/south/db/generic.py", line 1076, in really_send_create_signal
        db=self.db_alias,
      File "venv/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 185, in send
        response = receiver(signal=self, sender=sender, **named)
      File "venv/lib/python2.7/site-packages/django/contrib/contenttypes/management.py", line 81, in update_contenttypes
        ct.delete()
      File "venv/lib/python2.7/site-packages/django/db/models/base.py", line 695, in delete
        collector.delete()
      File "venv/lib/python2.7/site-packages/django/db/models/deletion.py", line 260, in delete
        qs._raw_delete(using=self.using)
      File "venv/lib/python2.7/site-packages/django/db/models/query.py", line 476, in _raw_delete
        sql.DeleteQuery(self.model).delete_qs(self, using)
      File "venv/lib/python2.7/site-packages/django/db/models/sql/subqueries.py", line 85, in delete_qs
        self.get_compiler(using).execute_sql(None)
      File "venv/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 782, in execute_sql
        cursor.execute(sql, params)
      File "venv/lib/python2.7/site-packages/django/db/backends/util.py", line 69, in execute
        return super(CursorDebugWrapper, self).execute(sql, params)
      File "venv/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
        return self.cursor.execute(sql, params)
      File "venv/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
        six.reraise(dj_exc_type, dj_exc_value, traceback)
      File "venv/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
        return self.cursor.execute(sql, params)
    ProgrammingError: relation "genericm2m_relatedobject" does not exist
    LINE 1: DELETE FROM "genericm2m_relatedobject" WHERE "genericm2m_rel...
                        ^

It appears to get triggered through the `post_delete` signal:

    > venv/lib/python2.7/site-packages/django/db/models/deletion.py(282)delete()
        281                         signals.post_delete.send(
    --> 282                             sender=model, instance=obj, using=self.using
        283                         )

    ipdb> model
    <class 'django.contrib.contenttypes.models.ContentType'>
    ipdb> obj
    <ContentType: foo file>

Django 1.6.2, django-generic-m2m==0.2.2

**Comment by jpic** [comment]
@blueyed that was fixed upstream right ?

**Comment by blueyed** [comment]
Not sure, but will close it anyway.

**Comment by jpic** [comment]
Well, we don't get in that situation anymore now that we check INSTALLED_APPS ^^
