### ISSUE TITLE
Unable to install package with pip: python setup.py egg_info failed

### ISSUE THREAD

**Issue by kpagcha** [coleifer/django-generic-m2m#25]
I have been spending hours on this and I just cannot get it to work. When trying to install with `pipi install django-generic-m2m` I just keep getting an exception raised by the `convert_path` method in `utils.py` from `distutils`. It says ` ValueError: path 'example/' cannot end with '/'`.

This is the full stack trace:

```
  Using cached django-generic-m2m-0.3.0.tar.gz
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info\django_generic_m2m.egg-info
    writing pip-egg-info\django_generic_m2m.egg-info\PKG-INFO
    writing top-level names to pip-egg-info\django_generic_m2m.egg-info\top_level.txt
    writing dependency_links to pip-egg-info\django_generic_m2m.egg-info\dependency_links.txt
    writing manifest file 'pip-egg-info\django_generic_m2m.egg-info\SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'pip-egg-info\django_generic_m2m.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching 'LICENSE.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\pablo\appdata\local\temp\pip-build-dcl6j_\django-generic-m2m\setup.py", line 32, in <module>
        test_suite='runtests.runtests',
      File "c:\python27\lib\distutils\core.py", line 152, in setup
        dist.run_commands()
      File "c:\python27\lib\distutils\dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "c:\python27\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "c:\python27\lib\site-packages\setuptools\command\egg_info.py", line 279, in run
        self.find_sources()
      File "c:\python27\lib\site-packages\setuptools\command\egg_info.py", line 306, in find_sources
        mm.run()
      File "c:\python27\lib\site-packages\setuptools\command\egg_info.py", line 535, in run
        self.read_template()
      File "c:\python27\lib\site-packages\setuptools\command\sdist.py", line 113, in __read_template_hack
        orig.sdist.read_template(self)
      File "c:\python27\lib\distutils\command\sdist.py", line 315, in read_template
        self.filelist.process_template_line(line)
      File "c:\python27\lib\site-packages\setuptools\command\egg_info.py", line 334, in process_template_line
        (action, patterns, dir, dir_pattern) = self._parse_template_line(line)
      File "c:\python27\lib\distutils\filelist.py", line 105, in _parse_template_line
        dir_pattern = convert_path(words[1])
      File "c:\python27\lib\distutils\util.py", line 202, in convert_path
        raise ValueError, "path '%s' cannot end with '/'" % pathname
    ValueError: path 'example/' cannot end with '/'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\pablo\appdata\local\temp\pip-build-dcl6j_\django-generic-m2m\

```

**Comment by coleifer** [comment]
Yeah, I guess you're the first person on windows to install the package. I removed the trailing slash from the offending line in MANIFEST.in and pushed a new release. Try again and let me know if you're still experiencing issues. The latest version is now 0.3.1.
